### ISSUE TITLE
我要怎么知道它发挥了作用？

### ISSUE THREAD

**Issue by dubhe2015** [mili-tan/AuroraDNS.GUI#12]
才下载，但是不知道是否发挥了作用！@！！！

**Comment by mili-tan** [comment]
额啊…您将它设为默认DNS服务器了吗，设定完成后，您可以随意使用nslookup来查询解析结果。
如果服务器为 `Address:  127.0.0.1` 那么就代表设定成功，他就可以正常发挥作用了。
