### ISSUE TITLE
不好意思，求教用法

### ISSUE THREAD

**Issue by 123ysys** [mili-tan/AuroraDNS.GUI#14]
希望能够教教小白用法。它不是一个exe文件吗？

**Comment by mili-tan** [comment]
麻烦请描述一下您遇到了什么问题，方便我能够解决。

**Comment by 123ysys** [comment]
是这样的，限与自己的知识水平，我只知道大多数移动终端会使用apk的软件，然后电脑上是exe软件。我在发布列表上的文件夹里似乎没有发现这两个格式的安装包。不知道该如何获取。
如果这是需要用户在软件中输入命令的话，还是希望您能给个步骤；如果不需要，请告诉我该下载哪个文件。谢谢。

**Comment by mili-tan** [comment]
请到 https://github.com/mili-tan/AuroraDNS.GUI/releases 下载压缩包 解压后运行
