### ISSUE TITLE
want you to prepare English notation

### ISSUE THREAD

**Issue by kometchtech** [mili-tan/AuroraDNS.GUI#17]
Chinese notation can be used somehow, but I do not understand some meanings, so I hope that you can prepare English notation, such as switching to English notation if possible.

(Im Japanese but I can use it if I have English notation)

**Comment by mili-tan** [comment]
Thank you for your interest in it.

About i18n/L10n and support other languages, Being planned, but not now.
May be in the near future, Maybe.
I have a little busy in recent months. no much time for development.

And sorry for my poor English.
