### ISSUE TITLE
[feature] Blacklist/whitelist, IPv6 & host files

### ISSUE THREAD

**Issue by Riajyuu** [mili-tan/AuroraDNS.GUI#19]
Some feature requests from [simple DNSCrypt](https://github.com/bitbeans/SimpleDnsCrypt):

- [ ] Adding blacklist/whitelist. It would be better if you return 0.0.0.0 instead of empty response for blacklist entries.
- [ ] Stop IPv6, aka send empty message to IPv6 server. This accelerate querying when you don't have IPv6 access.
- [ ] Support remote host files. Better if there is a management UI.
- [ ] UI to manage virtual network driver.

**Comment by mili-tan** [comment]
你好，非常感谢你的意见与建议
关于 blacklist/whitelist 已经有重定向名单作为替代了，用途和格式是和 Hosts 文件一致。原本也是有blacklist 的，但是因为考量想要精简化，就从 UI 隐藏了可以手动更改配置文件来使用。
停用 IPv6 已经在计划中了，大概最近的版本里面就会添加。
另外我好像不太明白您指的 remote host files 是什么，可以麻烦详细说明一下吗？
最后关于 虚拟网络适配器，实在抱歉可能不会在近期的计划之中呢，因为实在是有些复杂，以后我会试试看的。
