### ISSUE TITLE
经常显示：DNS服务器无法启动：端口被占用

### ISSUE THREAD

**Issue by RushFTK** [mili-tan/AuroraDNS.GUI#2]
是不是该系统默认占用了127.0.0.1:1080?
我不知道该提供哪方面的详细信息，系统Windows10但是装了很多软件无法排查哪些之间冲突……
希望给出常见错误处理和故障说明的页面方便自查，谢谢了:(

**Comment by mili-tan** [comment]
是检查53端口的占用
您可以试试看`netstat -ano|findstr 53`来查看53端口的占用的情况
然后可以通过对应PID `tasklist | findstr [PID]` 反查到是何程序正在占用端口

**Comment by RushFTK** [comment]
![image](https://user-images.githubusercontent.com/20500319/51160767-85471780-18ca-11e9-9812-fa18d0164b47.png)  
您好，相关信息如图显示
看起来是一个正常的通用主进程导致的，其由服务SharedAccess创建  
![image](https://user-images.githubusercontent.com/20500319/51160866-e40c9100-18ca-11e9-9b11-bd6f512c8f95.png)  
请问是否能够在未来推出自定义监听端口功能？

**Comment by mili-tan** [comment]
非常抱歉，目前暂时没有打算添加自定义端口功能，而且似乎Windows也没有办法使用非标准端口的DNS服务器。
另外关于 SharedAccess 占用 53 端口的问题 也许 #https://github.com/Azure/service-fabric-issues/issues/803#issuecomment-361706326 能够为您带来一些帮助

**Comment by loy23333aI** [comment]
> 非常抱歉，目前暂时没有办法添加自定义端口功能，而且似乎Windows也没有办法使用非标准端口的 DNS 服务器。
> 另外关于 SharedAccess 占用 53 端口的问题 也许 [Azure/service-fabric-issues#803 (comment)](https://github.com/Azure/service-fabric-issues/issues/803#issuecomment-361706326) 能够为您带来一些帮助

关掉天杀的hyper-v就行了
