### ISSUE TITLE
【功能建议】能否国内IP用国内DNS解析，国外IP用国外DNS解析？

### ISSUE THREAD

**Issue by LittleGrocery** [mili-tan/AuroraDNS.GUI#20]
能否国内IP用国内DNS服务器解析，国外IP用国外DNS服务器解析？这样本地化也会更好，国外访问速度也能达到保证

**Comment by mili-tan** [comment]
感谢您的建议 已经有了ChinaList功能了 现在可以修改配置文件启用ChinaList然后目录下新建一个china.list列表文件（每行一个域名）列表中的域名将会使用 DNSPod D+ HTTPDNS 来解析
另外是无法根据IP来区分的，因为DNS解析的过程是域名对应到IP，解析前是获得不到IP的。

**Comment by anyran** [comment]
关注到了您的这个项目，很不错，关于这个国内外解析的问题，同样感觉是一个比较大的痛点，虽然使用chinalist这样的方式可以实现一部分需求，但是像一些视频网站，本身会采用一些单独的域名用作静态内容或者版权内容，不太方便全部都添加到list内。
提一个建议吧，供参考。可以先使用国内DNS进行解析，解析出来的地址是国外的，再采用国外DNS重新解析，返回最终值，或者国内外同时查询，通过返回的IP的位置决定最终返回哪一个地址作为程序的输出值，同时将结果缓存起来，应该能解决这个痛点。谢谢~
