### ISSUE TITLE
[自定义监听IP地址]设置显示有误

### ISSUE THREAD

**Issue by JokerQyou** [mili-tan/AuroraDNS.GUI#21]
如图，如果开放为 `0.0.0.0` （想给局域网内其他电脑使用），保存后似乎确实生效，但设置窗口如果再次打开，这个开关还是显示为关闭状态。版本是 `1.0.0.0 (190701.Releases)`

![image](https://user-images.githubusercontent.com/1465267/60787749-621c6700-a18d-11e9-9e02-de20df9f2a4a.png)

**Comment by mili-tan** [comment]
感谢你的反馈 我检查了一下 这似乎是UI逻辑上的问题并不影响功能 我最近的版本修复的
