### ISSUE TITLE
同时监听IPv6地址

### ISSUE THREAD

**Issue by SkiTiSu** [mili-tan/AuroraDNS.GUI#22]
因为Windows 10必然优先使用IPv6的DNS服务器（已查找无数资料无果，唯一方法是把IPv6关闭），所以尴尬的是由于本程序不支持监听IPV6（尝试将自定义监听地址改为`::`但是好像没有用），即使已经将IPv4的DNS地址设置为127.0.0.1，系统貌似并不会使用（由nslookup看出）

**Comment by mili-tan** [comment]
感谢你的反馈 我检查了一下 我这边测试将自定义监听地址改为`::`好像是有效的呢
另外因为一些原因修改自定义监听地址要重启程序才生效呢（一些逻辑问题，我会尝试修正的）
然后嘛关于Windows 10优先使用IPv6的DNS服务器也许和系统IPv4与IPv6优先级有关系？
也许可以尝试 [https://support.microsoft.com/zh-cn/help/929852/guidance-for-configuring-ipv6-in-windows-for-advanced-users](https://support.microsoft.com/zh-cn/help/929852/guidance-for-configuring-ipv6-in-windows-for-advanced-users) 的“在前缀策略中优先使用 IPv4 over IPv6”

**Comment by SkiTiSu** [comment]
感谢回复，请问可以同时监听v4和v6地址嘛，打算把这个装在NAS里面，局域网直接指向这个地址了。后面贴的微软官方链接等一切谷歌能找到资料我都试过了，只是在解析出来后优先使用v4地址，但解析本身使用的DNS服务器，还是优先用v6且没有方法能够修改= =

**Comment by mili-tan** [comment]
同时监听v4和v6地址 大概需要研究下…… 
应该可以通过端口转发来实现效果？

**Comment by mili-tan** [comment]
已在最新版本添加tcp转发

**Comment by CCRcmcpe** [comment]
请问tcp转发选项在哪呢？
用的200201 - Release，用::1解析无响应
