### ISSUE TITLE
dns 还是被污染

### ISSUE THREAD

**Issue by huanghuang1993** [mili-tan/AuroraDNS.GUI#23]
| - Catch WebException : 未将对象引用设置到对象的实例。 | p9.qhimg.com. | https://dns.google/resolve
| -- SecondDoH : https://1.0.0.1/dns-query
| - Catch WebException : 未将对象引用设置到对象的实例。 | p1.qhimg.com. | https://dns.google/resolve
| -- SecondDoH : https://1.0.0.1/dns-query
| - Catch WebException : 未将对象引用设置到对象的实例。 | p9.qhimg.com. | https://1.0.0.1/dns-query
| -- SecondDns : 223.5.5.5
| 2019/8/4 12:04:10 127.0.0.1 : logic2.updrv.com. | A
| - Catch WebException : 未将对象引用设置到对象的实例。 | p8.qhimg.com. | https://dns.google/resolve
| -- SecondDoH : https://1.0.0.1/dns-query
| - Catch WebException : 未将对象引用设置到对象的实例。 | p1.qhimg.com. | https://1.0.0.1/dns-query
| -- SecondDns : 223.5.5.5
| 2019/8/4 12:04:10 127.0.0.1 : cloud.browser.360.cn. | A
| - Catch WebException : 未将对象引用设置到对象的实例。 | p3.qhimg.com. | https://dns.google/resolve
| -- SecondDoH : https://1.0.0.1/dns-query
| - Catch WebException : 未将对象引用设置到对象的实例。 | p8.qhimg.com. | https://1.0.0.1/dns-query
| -- SecondDns : 223.5.5.5
| 2019/8/4 12:04:11 127.0.0.1 : toutyrater.github.io. | A
| - Catch WebException : 未将对象引用设置到对象的实例。 | p5.qhimg.com. | https://dns.google/resolve
| -- SecondDoH : https://1.0.0.1/dns-query
| - Catch WebException : 未将对象引用设置到对象的实例。 | p3.qhimg.com. | https://1.0.0.1/dns-query
| -- SecondDns : 223.5.5.5
| - Catch WebException : 未将对象引用设置到对象的实例。 | dispatch.updrv.com. | https://dns.google/resolve
| -- SecondDoH : https://1.0.0.1/dns-query
| - Catch WebException : 未将对象引用设置到对象的实例。 | p5.qhimg.com. | https://1.0.0.1/dns-query
| -- SecondDns : 223.5.5.5
| - Catch WebException : 未将对象引用设置到对象的实例。 | izy.updrv.com. | https://dns.google/resolve
| -- SecondDoH : https://1.0.0.1/dns-query
| - Catch WebException : 未将对象引用设置到对象的实例。 | dispatch.updrv.com. | https://1.0.0.1/dns-query
| -- SecondDns : 223.5.5.5
| - Catch WebException : 未将对象引用设置到对象的实例。 | izy.updrv.com. | https://1.0.0.1/dns-query
| - Catch WebException : 未将对象引用设置到对象的实例。 | hashtourl1.updrv.com. | https://dns.google/resolve
| -- SecondDoH : https://1.0.0.1/dns-query
| -- SecondDns : 223.5.5.5
| - Catch WebException : 未将对象引用设置到对象的实例。 | hashtourl1.updrv.com. | https://1.0.0.1/dns-query
| -- SecondDns : 223.5.5.5
| - Catch WebException : 未将对象引用设置到对象的实例。 | dsearch2.updrv.com. | https://dns.google/resolve
| -- SecondDoH : https://1.0.0.1/dns-query
| - Catch WebException : 未将对象引用设置到对象的实例。 | dsearch2.updrv.com. | https://1.0.0.1/dns-query
| -- SecondDns : 223.5.5.5
| 2019/8/4 12:04:19 127.0.0.1 : autoupdater.updrv.com. | A
| 2019/8/4 12:04:19 127.0.0.1 : autoupdater.updrv.com. | A
| 2019/8/4 12:04:20 127.0.0.1 : media.update.updrv.com. | A
| 2019/8/4 12:04:20 127.0.0.1 : dtl.update.updrv.com. | A
| - Catch WebException : 未将对象引用设置到对象的实例。 | s3.nzbdw.com. | https://dns.google/resolve
| -- SecondDoH : https://1.0.0.1/dns-query
| - Catch WebException : 未将对象引用设置到对象的实例。 | s3.nzbdw.com. | https://1.0.0.1/dns-query
| -- SecondDns : 223.5.5.5
| 2019/8/4 12:04:22 127.0.0.1 : api.github.com. | A
| - Catch WebException : 未将对象引用设置到对象的实例。 | logic2.updrv.com. | https://dns.google/resolve
| -- SecondDoH : https://1.0.0.1/dns-query
| - Catch WebException : 未将对象引用设置到对象的实例。 | cloud.browser.360.cn. | https://dns.google/resolve
| -- SecondDoH : https://1.0.0.1/dns-query

**Comment by mili-tan** [comment]
请检查您能否正常访问 https://dns.google/resolve
