### ISSUE TITLE
允许备用DNS服务器留空

### ISSUE THREAD

**Issue by roshad** [mili-tan/AuroraDNS.GUI#26]
此栏不留空，DNS泄露测试就有5成以上运营商劫持的记录。

**Comment by mili-tan** [comment]
感谢你的建议 之后会考虑允许设置备用DNS为空
目前您可以手动在系统网络适配器设置中手动去掉备用DNS

**Comment by sky5454** [comment]
> 此栏不留空，DNS泄露测试就有5成以上运营商劫持的记录。

你好，我好像也遇到这个问题了，会不会是因为现在的备用 DNS 已经不是以前那种`当首选 DNS 不可用时才使用`，而是备用 DNS 和首选 DNS 混合使用了？

**Comment by roshad** [comment]
> > 此栏不留空，DNS泄露测试就有5成以上运营商劫持的记录。
> 
> 你好，我好像也遇到这个问题了，会不会是因为现在的备用 DNS 已经不是以前那种`当首选 DNS 不可用时才使用`，而是备用 DNS 和首选 DNS 混合使用了？

https://serverfault.com/questions/84291/how-does-windows-decide-which-dns-server-to-use-when-resolving-names
我也查到了一些，在1秒切备用这一点上是相同的。但这两文都不是很新，目下情况可能有异同。

**Comment by mili-tan** [comment]
已在最新版本添加

**Comment by roshad** [comment]
我更仔细地看了一下软体的运行模式, 发现 备用dns似乎是不可或缺的.  因主辅doh的ip都需要寻常dns来得到. 
那么, 此次为免dns劫持所作的更动, 就应该是 允许不把备用dns填入系统备用dns栏, 而非 允许留空备用dns栏了.

**Comment by sky5454** [comment]
> 我更仔细地看了一下软体的运行模式, 发现 备用dns似乎是不可或缺的. 因主辅doh的ip都需要寻常dns来得到.
> 那么, 此次为免dns劫持所作的更动, 就应该是 允许不把备用dns填入系统备用dns栏, 而非 允许留空备用dns栏了.

更应该说：内置几个 DNS 来查询 DoH 服务器的 ip 地址

**Comment by mili-tan** [comment]
> 
> 
> > 我更仔细地看了一下软体的运行模式, 发现 备用dns似乎是不可或缺的. 因主辅doh的ip都需要寻常dns来得到.
> > 那么, 此次为免dns劫持所作的更动, 就应该是 允许不把备用dns填入系统备用dns栏, 而非 允许留空备用dns栏了.
> 
> 更应该说：内置几个 DNS 来查询 DoH 服务器的 ip 地址

已经做了一些更改 备用 DNS 为空时将会使用 1.0.0.1 的 DoH 作启动查询
