### ISSUE TITLE
无法完全禁用日志

### ISSUE THREAD

**Issue by Riajyuu** [mili-tan/AuroraDNS.GUI#29]
![image](https://user-images.githubusercontent.com/16912240/66548807-817eb380-eb31-11e9-8b0e-4e1938cf6d68.png)

如图所示，无论如何设置，始终会留有log文件

**Comment by mili-tan** [comment]
您好 在程序出错 或者网络连接失败的时候还是会生成错误日志的。

**Comment by Riajyuu** [comment]
>程序将会在退出时清理当日之前产生的日志

是个办法，不过如图所示，我的运行目录是 OneDrive 内，所以对于这类高频操作的文件，退出时再清理仍有可能造成不可避免的冲突，因为退出的时候往往就是关机的时候，OneDrive 一般已经来不及处理
