### ISSUE TITLE
能不能提供完全无代理的选项

### ISSUE THREAD

**Issue by standritsu** [mili-tan/AuroraDNS.GUI#30]
即使关闭代理，软件仍然会走系统代理，希望可以有完全不走代理的设置。

**Comment by mili-tan** [comment]
你好 在关闭代理的情况下应该不会使用系统代理的啊……

**Comment by standritsu** [comment]
我在关闭代理的情况下，在系统设置的代理的日志窗口里面看见了DOH服务器的连接请求。

**Comment by mili-tan** [comment]
您好 感谢您的反馈 已尝试修正。
