### ISSUE TITLE
能不能加一个新功能?

### ISSUE THREAD

**Issue by wysnxzm** [mili-tan/AuroraDNS.GUI#31]
思路是这样的:访问baidu.com使用多个DNS例如223.5.5.5 114.114.114.144 获得不同的ip后进行ping,使用延迟最低的ip,可以做缓存不会对dns服务器有很大负担
这种方法可以解决dns返回的ip无效或者延迟过高的问题
还可以解决轻度dns污染与doh的本意不谋而合

**Comment by mili-tan** [comment]
您好，感谢你的建议。
但是本项目主要专注于 DNS over HTTPS，而且我认为这样似乎并不能解决 DNS 污染问题，更没有办法解决 DNS 查询未加密导致查询记录泄露的问题。
另外据我所知，似乎有类似思路的实现，也许你应该试试看 [SmartDNS](https://github.com/pymumu/smartdns)。

**Comment by wysnxzm** [comment]
> 您好，感谢你的建议。
> 但是本项目主要专注于 DNS over HTTPS，而且我认为这样似乎并不能解决 DNS 污染问题，更没有办法解决 DNS 查询未加密导致查询记录泄露的问题。
> 另外据我所知，似乎有类似思路的实现，也许你应该试试看 [SmartDNS](https://github.com/pymumu/smartdns)。

还有DNS Chooser, SmartDNS是路由器的并不是很方便
专注于doh很棒,但是这个功能可以锦上添花让网络更加快捷
如果单纯的只是做了一个dnscrypt-proxy的客户端未免太可惜毕竟同类的产品过于繁多
感谢你的回答,如果你觉得这个功能能够促进网络发展的话,可以在某一天实现
