### ISSUE TITLE
允许禁用公网 IP 查询

### ISSUE THREAD

**Issue by Riajyuu** [mili-tan/AuroraDNS.GUI#32]
对于有些用户而言 这是一个隐私风险
不过同时 禁用公网 IP 查询就意味着不再使用区域化查询

PS （这是代发的）

**Comment by mili-tan** [comment]
你好
可以打开自定义 EDNS Client Subnet IP 选项 
并将自定义 EDNS Client Subnet IP 设为 0.0.0.0 即可
这也是Google DNS和1.1.1.1定义的隐私化查询。

**Comment by Riajyuu** [comment]
我指的是
![image](https://user-images.githubusercontent.com/16912240/71389433-43ebdb80-25f4-11ea-99ed-f285707aadbf.png)

**Comment by mili-tan** [comment]
你好 打开自定义 EDNS Client Subnet IP 选项后将不再使用 WhatMyIP API

**Comment by Riajyuu** [comment]
> 将不再使用 WhatMyIP API 返回的结果

我的意思是 直接不对外查询公网IP。。。。。。。。

**Comment by mili-tan** [comment]
在刚刚已经做了一些更改 
自定义 EDNS Client Subnet IP 选项设为 0.0.0.0 后启动时将不再请求 WhatMyIP API
下次Release中将会包含，感谢您的建议！
