### ISSUE TITLE
窗口半透明🤣

### ISSUE THREAD

**Issue by loy23333aI** [mili-tan/AuroraDNS.GUI#33]
![image](https://user-images.githubusercontent.com/23432137/72734240-4847ec00-3bd4-11ea-80b3-300c6c2e3f34.png)
不晓得为啥子是这个样子的，是正常的吗，看上去有点难受的亚子。
[DxDiag.txt](https://github.com/mili-tan/AuroraDNS.GUI/files/4086632/DxDiag.txt)

**Comment by mili-tan** [comment]
你好 窗体半透明是正常的…
模糊的话应该是因为运行了多个进程…

**Comment by loy23333aI** [comment]
> 你好 窗体半透明是正常的…
> 模糊的话应该是因为运行了多个进程…

找到原因了。。dnscrypt没删干净。。53端口被占用了🤣😪
百忙之中搅扰，抱歉😪😥
