### ISSUE TITLE
默认的neatDNS，我用网易DNS检测工具看了看，好像还是走的119.29.29.29啊

### ISSUE THREAD

**Issue by yeezylife** [mili-tan/AuroraDNS.GUI#34]
请问是设置未生效么？还是直接调用了备用的公共DNS
“您的DNS地址信息:183.61.51.140 广东省深圳市电信” “您的DNS地址信息: 58.53.186.94 湖北省武汉市电信”  主DOH用默认的neatDNS  检测的地址在这两个地点变化，，

**Comment by yeezylife** [comment]
现在又变成  “您的DNS地址信息: 58.53.186.94 湖北省武汉市电信”

**Comment by mili-tan** [comment]
您好
请您清空DNS缓存重启浏览器以后检查是否生效。
中科大NeatDNS `58.53.186.94 湖北省武汉市电信` 与 `202.141.162.123 安徽省合肥市电信` 似乎是正常的。
一般DNS出口IP不一定是会是DoH服务器IP。
如果您始终发生 DNS 泄露并且非常在意，可以将软件内与系统中的 备用DNS 直接设为空，一般就可解决问题。

**Comment by yeezylife** [comment]
> 您好
> 请您清空DNS缓存重启浏览器以后检查是否生效。
> 中科大NeatDNS `58.53.186.94 湖北省武汉市电信` 与 `202.141.162.123 安徽省合肥市电信` 似乎是正常的。
> 一般DNS出口IP不一定是会是DoH服务器IP。
> 如果您始终发生 DNS 泄露并且非常在意，可以将软件内与系统中的 备用DNS 直接设为空，一般就可解决问题。

感谢你的回复，由于我自己也是湖北的，看到检测显示湖北武汉，我以为是走了自动获取的运营商dns,现在我明白了，目前刷新也基本没有跳到备用dns的情况了。

**Comment by mili-tan** [comment]
> 
> 
> > 您好
> > 请您清空DNS缓存重启浏览器以后检查是否生效。
> > 中科大NeatDNS `58.53.186.94 湖北省武汉市电信` 与 `202.141.162.123 安徽省合肥市电信` 似乎是正常的。
> > 一般DNS出口IP不一定是会是DoH服务器IP。
> > 如果您始终发生 DNS 泄露并且非常在意，可以将软件内与系统中的 备用DNS 直接设为空，一般就可解决问题。
> 
> 感谢你的回复，由于我自己也是湖北的，看到检测显示湖北武汉，我以为是走了自动获取的运营商dns,现在我明白了，目前刷新也基本没有跳到备用dns的情况了。

祝身体安康，万事小心。
