### ISSUE TITLE
DoH API 类型选择

### ISSUE THREAD

**Issue by sfc9982** [mili-tan/AuroraDNS.GUI#35]
Google DNS提供了两种API，分别为:
RFC 8484 (GET and POST) https://dns.google/dns-query
JSON API (GET) https://dns.google/resolve?
请问应该选择哪种作为DoH服务器使用？

问题二:
https://dns.google/resolve?
该链接末尾的问号标识符是否需要在客户端的Doh服务器中添加（缺省地址无问号）

感谢您的耐心

**Comment by mili-tan** [comment]
您好
目前DNS Message(RFC 8484)与DNS Json是自适应支持的，二者均可。但是我没有对DNS Message进行更多测试，可能还存在一些小问题或者不稳定，还请谅解。
另外地址可以参考自带列表中的地址，不需添加"?"。

**Comment by sfc9982** [comment]
> 您好 目前DNS Message(RFC 8484)与DNS Json是自适应支持的，二者均可。但是我没有对DNS Message进行更多测试，可能还存在一些小问题或者不稳定，还请谅解。 另外地址可以参考自带列表中的地址，不需添加"?"。

谢谢
Closed
