### ISSUE TITLE
Lang

### ISSUE THREAD

**Issue by Evertonlps** [mili-tan/AuroraDNS.GUI#37]
Only Chinese?

**Comment by mili-tan** [comment]
Thank you for your interest in it.

About support other languages, Being planned, but not now.
May be in the near future, Maybe.
And Windows 10 seems to be add system support for DNS over HTTPS, I am thinking if there is need to support other languages.

And sorry for my poor English.

**Comment by Evertonlps** [comment]
> Thank you for your interest in it.
> 
> About support other languages, Being planned, but not now.
> May be in the near future, Maybe.
> And Windows 10 seems will add system support for DNS over HTTPS, I am thinking if there is need to support other languages.
> 
> And sorry for my poor English.

I understand, I don't use Windows 10 and I don't intend to use, just Linux and Windows 7, that's why I got interested.
About English, I also do not speak :D I am Brazilian, thank you very much for answering, a hug to you friend and success in your projects.
