### ISSUE TITLE
程序有时会崩溃

### ISSUE THREAD

**Issue by Xin9-Liu** [mili-tan/AuroraDNS.GUI#39]
有时设置里的输入框会有重影
![image](https://user-images.githubusercontent.com/44594408/76723158-4f791980-6781-11ea-91ad-185bdcd7bf32.png)
这时候dns解析就不稳定。用http://nstool.netease.com/ 测试，dns地址会在ISP的dns和自定义的dns间反复跳动。
重新打开设置后，就显示一片白色。重新启动才能恢复。
![image](https://user-images.githubusercontent.com/44594408/76723365-f362c500-6781-11ea-8e8e-597b7dd3e257.png)

**Comment by mili-tan** [comment]
你好 我曾经也偶然遇见过这样的问题
但是我无法定位故障，进行调试也未发现错误
但是我猜测也许和系统休眠后恢复有关

**Comment by Xin9-Liu** [comment]
我开机后没有休眠，也出现了这种情况，而且是反复出现。

**Comment by mili-tan** [comment]
你好，
如果你的日志中存在相关的错误信息的话，欢迎提供给我。
如果不存在错误信息，这个问题难以被定位，也很难进行修复。

**Comment by Xin9-Liu** [comment]
好的




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Milkey Tan"<notifications@github.com&gt;; 
发送时间: 2020年3月16日(星期一) 中午12:52
收件人: "mili-tan/AuroraDNS.GUI"<AuroraDNS.GUI@noreply.github.com&gt;; 
抄送: "w"<1250449439@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [mili-tan/AuroraDNS.GUI] 程序有时会崩溃 (#39)





 
你好，
 如果你的日志中存在相关的错误信息的话，欢迎提供给我。
 如果不存在错误信息，这个问题难以被定位，也很难进行修复。

**Comment by mili-tan** [comment]
我看到据说是BackgroundWorker可能在长时间运行时遇到问题
我尝试把它更换成了Task
https://ci.appveyor.com/project/mili-tan/auroradns-gui/builds/31488049/artifacts
你可以从这里下载CI生成的编译使用 试试看问题能否得到解决

**Comment by Xin9-Liu** [comment]
我试试

**Comment by Xin9-Liu** [comment]
问题还是存在

**Comment by mili-tan** [comment]
那是真的不知道怎么办了😂
