### ISSUE TITLE
有啥用

### ISSUE THREAD

**Issue by Sun-Hong** [mili-tan/AuroraDNS.GUI#4]
用了反而连不了google翻译了：）

**Comment by mili-tan** [comment]
如果可以的话请提供一下错误日志，
似乎目前默认的DoH接口`https://1.0.0.1/dns-query`在中国大陆的一些地区似乎并不能很好的访问，您可以尝试一下修改设置中的DoH接口选项，使用其他接口。
另外考虑到受到屏蔽与1.1.1.1和1.0.0.1似乎时常被当作内网ip来使用，下一个Release版本中将会将默认的DoH接口更换为`https://dns.cloudflare.com/dns-query`
