### ISSUE TITLE
IPv6支持

### ISSUE THREAD

**Issue by standritsu** [mili-tan/AuroraDNS.GUI#40]
日志文件被这条以每秒2-3K的速度在刷屏

   在 System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   在 AuroraGUI.Tools.IpTools.ResolveNameIpAddress(String name)
System.ArgumentOutOfRangeException: 索引超出范围。必须为非负值并小于集合大小。
参数名: index

**Comment by mili-tan** [comment]
你好
也请粘帖一下您的配置，很可能是配置有误，或者DoH服务器的错误导致查询结果为空。

**Comment by standritsu** [comment]
{
"Listen" : "::1",
"SecondDns" : "119.29.29.29",
"BlackList" : false,
"ChinaList" : false,
"RewriteList" : false,
"DebugLog" : false,
"EDnsCustomize" : false,
"EDnsClientIp" : "0.0.0.0",
"ProxyEnable" : false,
"HttpsDns" : "https://v6.rubyfish.cn/dns-query",
"SecondHttpsDns" : "https://neatdns.ustclug.org/resolve",
"Proxy" : "127.0.0.1:1080",
"EnableDnsCache" : false,
"EnableDnsMessage" : false,
"EnableAutoCleanLog" : true,
"Ipv6Disable" : false,
"Ipv4Disable" : false,
"StartupOverDoH" : false,
"AllowSelfSignedCert" : false,
"AllowAutoRedirect" : true,
"HTTPStatusNotify" : false,
"EnableHttp2" : false 
}

**Comment by mili-tan** [comment]
你好
程序默认的使用的WebClient似乎暂时不支持IPv6
请你尝试将"EnableHttp2"设为true尝试是否能够解决问题（我不确定这是否可行）
或者您可以尝试换用支持IPv4的DoH服务器

很抱歉，因为条件限制我没有在IPv6环境下进行很多测试，我不确定是否可用。

**Comment by standritsu** [comment]
http2的话不能正常运行

**Comment by mili-tan** [comment]
那请先换用IPv4吧 我会尝试添加v6支持的

**Comment by mili-tan** [comment]
https://ci.appveyor.com/project/mili-tan/auroradns-gui/builds/31517855/artifacts
你好 我尝试修正了一些问题 你可以下载CI的编译 然后尝试清空配置文件以后使用 看看是否能够解决问题

**Comment by standritsu** [comment]
问题解决，包括HTTP2也能正常使用
