### ISSUE TITLE
遇到性能问题，有时占用大量资源

### ISSUE THREAD

**Issue by loy23333aI** [mili-tan/AuroraDNS.GUI#42]
![微信图片_20200406175732](https://user-images.githubusercontent.com/23432137/78546617-49320680-7830-11ea-8203-72b3e3412365.jpg)
见附图，不知道遇到什么问题，无提示。点开也似乎是正常运行状态。

**Comment by mili-tan** [comment]
您好
能否提供日志 以便让我了解更多 另外请检查是否监听在0.0.0.0
