### ISSUE TITLE
运行一段时间后报错：无法创建新的堆栈防护页面

### ISSUE THREAD

**Issue by zhezhe168** [mili-tan/AuroraDNS.GUI#44]
运行一段时间后报错：无法创建新的堆栈防护页面

同样2台win7 sp1 64位电脑，环境都装了net framework 4.6.2，一台正常，一台报错这个

**Comment by mili-tan** [comment]
你好 
麻烦你提供更详细的日志，以便我定位故障和解决问题。
此外Windows7的生命周期已经结束，微软官方已经停止支援，本程序亦没有在Windows7环境下进行更多的测试，可能会发生一些意料之外情况，建议换用Windows10。

**Comment by zhezhe168** [comment]
安装了net framwork 4.6 4.8之后正常了
