### ISSUE TITLE
分享doh服务器地址

### ISSUE THREAD

**Issue by 1265578519** [mili-tan/AuroraDNS.GUI#47]
txy
https://dns.pub/dns-query
https://doh.pub/dns-query

ali
https://dns.alidns.com/dns-query
https://223.5.5.5/dns-query
https://223.6.6.6/dns-query
https://2400:3200::1/dns-query
https://2400:3200:baba::1/dns-query

**Comment by mili-tan** [comment]
您好
感谢你的提议，但是Alidns和腾讯dnspod的主地址已在列表中存在，我们不会添加子/备用服务器地址。
感谢你的理解。




 
---原始邮件---
发件人: "小樱"<notifications@github.com&gt;
发送时间: 2020年10月20日 01:21:30
收件人: "mili-tan/AuroraDNS.GUI"<AuroraDNS.GUI@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [mili-tan/AuroraDNS.GUI] 分享doh服务器地址 (#47)




 
txy
 https://dns.pub/dns-query
 https://doh.pub/dns-query
 
ali
 https://dns.alidns.com/dns-query
 https://223.5.5.5/dns-query
 https://223.6.6.6/dns-query
 https://2400:3200::1/dns-query
 https://2400:3200:baba::1/dns-query
