### ISSUE TITLE
QQ管家允许了注册表修改但是还是跳错，是杀毒软件的问题吗？

### ISSUE THREAD

**Issue by 1265578519** [mili-tan/AuroraDNS.GUI#48]
![1](https://user-images.githubusercontent.com/6442439/96490790-e0622700-1273-11eb-97a2-79114546e61c.png)
![2](https://user-images.githubusercontent.com/6442439/96490794-e1935400-1273-11eb-8f9b-39674bfc10c4.png)

手动修改网卡的DNS为127.0.0.1后可以正常使用

**Comment by mili-tan** [comment]
您好
请允许协议关联，谢谢。


 
---原始邮件---
发件人: "小樱"<notifications@github.com&gt;
发送时间: 2020年10月20日 01:31:19
收件人: "mili-tan/AuroraDNS.GUI"<AuroraDNS.GUI@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [mili-tan/AuroraDNS.GUI] QQ管家允许了注册表修改但是还是跳错，是杀毒软件的问题吗？ (#48)

**Comment by 1265578519** [comment]
> 您好 请允许协议关联，谢谢。

感谢恢复，刚才发现了，QQ管家还内置了一套猎鹰全景防御，被识别成可疑程序，被后台静默阻止了，没找到加白的地方，测试直接关闭注册表防护就行了
![image](https://user-images.githubusercontent.com/6442439/96491202-7a29d400-1274-11eb-8289-b02a5b19ac2f.png)
![image](https://user-images.githubusercontent.com/6442439/96491364-b826f800-1274-11eb-95be-afe61a2b48e2.png)
