### ISSUE TITLE
AuroraDNS.GUI退出时没有把网卡原来自动获得DNS的选项恢复

### ISSUE THREAD

**Issue by quaggalinux** [mili-tan/AuroraDNS.GUI#49]
AuroraDNS.GUI退出时没有把网卡原来自动获得DNS的选项恢复，还是被设置为127.0.0.1，希望可以改进为退出软件或关闭设置系统DNS开关时恢复网卡原来自动获得DNS的选项

**Comment by mili-tan** [comment]
你好
我曾经也这么想过，但是这样的逻辑在开机自启或关机的时候可能遇到问题，所以并没有实施。


 
---原始邮件---
发件人: "quaggalinux"<notifications@github.com&gt;
发送时间: 2020年10月23日 07:22:13
收件人: "mili-tan/AuroraDNS.GUI"<AuroraDNS.GUI@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [mili-tan/AuroraDNS.GUI] AuroraDNS.GUI退出时没有把网卡原来自动获得DNS的选项恢复 (#49)




 
AuroraDNS.GUI退出时没有把网卡原来自动获得DNS的选项恢复，还是被设置为127.0.0.1，希望可以改进为退出软件或关闭设置系统DNS开关时恢复网卡原来自动获得DNS的选项

**Comment by quaggalinux** [comment]
能否做一个与开机自启互斥的开关选项呢

**Comment by mili-tan** [comment]
你好 我在菜单中添加了一个“退出并重置系统DNS”的选项
你可以在[这里](https://ci.appveyor.com/project/mili-tan/auroradns-gui/build/artifacts)下载CI自动编译的测试版本试用。
