### ISSUE TITLE
无论是点选“退出”或“退出并重置系统DNS”都要点选两次才能退出

### ISSUE THREAD

**Issue by quaggalinux** [mili-tan/AuroraDNS.GUI#50]
无论是点选“退出”或“退出并重置系统DNS”都要点选两次才能退出，点选第一次是无论等多长时间都不会退出的

**Comment by mili-tan** [comment]
你好 请检查您是否存在未关闭窗口 当存在未关闭窗口时不存在这种情况。


 
---原始邮件---
发件人: "quaggalinux"<notifications@github.com&gt;
发送时间: 2020年10月24日 00:53:23
收件人: "mili-tan/AuroraDNS.GUI"<AuroraDNS.GUI@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [mili-tan/AuroraDNS.GUI] 无论是点选“退出”或“退出并重置系统DNS”都要点选两次才能退出 (#50)




 
无论是点选“退出”或“退出并重置系统DNS”都要点选两次才能退出，点选第一次是无论等多长时间都不会退出的
