### ISSUE TITLE
点选“重新启动”不会应用之前做的配置变更

### ISSUE THREAD

**Issue by quaggalinux** [mili-tan/AuroraDNS.GUI#51]
先变更配置，例如如更改备用DNS服务器IP，点确定，确认配置保存，然后点选“重新启动”，然后查看 ipconfig /all 的网卡DNS配置，备用DNS服务器还会是原来没有变更的服务器IP，这时需要退出程序，重新运行程序才会应用变更的配置

**Comment by mili-tan** [comment]
你好 程序内置的备用DNS仅用于两个DoH查询都失败时进行查询 并不会与系统备用DNS同步 只有你在重新设置系统DNS会同步&nbsp;
这是因为修改系统DNS需要以管理员权限执行CMD指令或程序本身具有管理员权限。


 
---原始邮件---
发件人: "quaggalinux"<notifications@github.com&gt;
发送时间: 2020年10月24日 00:59:13
收件人: "mili-tan/AuroraDNS.GUI"<AuroraDNS.GUI@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [mili-tan/AuroraDNS.GUI] 点选“重新启动”不会应用之前做的配置变更 (#51)




 
先变更配置，例如如更改备用DNS服务器IP，点确定，确认配置保存，然后点选“重新启动”，然后查看 ipconfig /all 的网卡DNS配置，备用DNS服务器还会是原来没有变更的服务器IP，这时需要退出程序，重新运行程序才会应用变更的配置
