### ISSUE TITLE
关于DoH服务器使用的建议

### ISSUE THREAD

**Issue by quaggalinux** [mili-tan/AuroraDNS.GUI#52]
我大概明白程序使用DoH的逻辑，先使用备用DNS服务器IP查询DoH服务器网址的IP，然后使用DoH服务器的查询结果通过127.0.0.1反馈给应用程序
但这有一个前提是备用DNS服务器IP必须是没有被屏蔽或UDP应答没有被污染的，如果出现这种状况，这个备用DNS服务器IP不会查出正确的DoH服务器网址的IP结果
在这个情况下不如给用户一个选项，直接使用DoH的IP方式查询，如“https://9.9.9.10/dns-query”，，然后备用DNS服务器IP直接写成127.0.0.1
因为现在很多DoH服务提供商为了避免原来DNS的污染直接签发了IP证书而不止是域名证书，让用户直接可以以IP的URL方式使用

**Comment by mili-tan** [comment]
您好 您应当需要确保您的备用DNS服务没有被屏蔽 或者您应该直接只用作为以IP作为主机名的DoH服务器
如果您期望以您之后方式提到的方式运行 请将备用DNS服务器IP置空 或修改config.json中的StartupOverDoH为true 这将通过1.0.0.1或9.9.9.9的DoH解析您的DoH服务器的域名 请注意 但是请注意 这是一个实验性的特征 没有经过过多的测试


 
---原始邮件---
发件人: "quaggalinux"<notifications@github.com&gt;
发送时间: 2020年10月24日 01:11:51
收件人: "mili-tan/AuroraDNS.GUI"<AuroraDNS.GUI@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [mili-tan/AuroraDNS.GUI] 关于DoH服务器使用的建议 (#52)




 
我大概明白程序使用DoH的逻辑，先使用备用DNS服务器IP查询DoH服务器网址的IP，然后使用DoH服务器的查询结果通过127.0.0.1反馈给应用程序
 但这有一个前提是备用DNS服务器IP必须是没有被屏蔽或UDP应答没有被污染的，如果出现这种状况，这个备用DNS服务器IP不会查出正确的DoH服务器网址的IP结果
 在这个情况下不如给用户一个选项，直接使用DoH的IP方式查询，如“https://9.9.9.10/dns-query”，，然后备用DNS服务器IP直接写成127.0.0.1
 因为现在很多DoH服务提供商为了避免原来DNS的污染直接签发了IP证书而不止是域名证书，让用户直接可以以IP的URL方式使用
