### ISSUE TITLE
奇怪的问题（201031 - Release）

### ISSUE THREAD

**Issue by quaggalinux** [mili-tan/AuroraDNS.GUI#53]
使用201031 - Release版本

设置备用dns为127.0.0.1

主DOH服务器选程序内置列表的第一项https://1.1.1.1/dns-query
备DOH服务器选程序内置列表的第二项https://1.0.0.1/dns-query

点选设置菜单顶上的清除DNS缓存，然后点确定，保存配置，退出程序，再重启程序，然后在CMD命令行打命令ipconfig /all确认网卡的主，备DNS地址均为127.0.0.1

按照我理解的逻辑理论上在这个设置下可能出现两种情况
第一，由于网卡的主，备DNS服务器地址均被设置为127.0.0.1，程序不能通过备用DNS地址查找DOH服务器，所以导致系统不能解析任何域名
第二，由于网卡的主，备DNS服务器地址均被设置为127.0.0.1，而由于在程序中选择了https://1.1.1.1/dns-query方式的直接IP访问DOH服务器方式，所以系统可以通过DOH查询到域名

但是实际情况非常奇怪，当按照前面的设置重启程序，然后在CMD命令行打命令ipconfig /all确认网卡的主，备DNS地址均为127.0.0.1
然后在CMD命令行打入nslookup www.baidu.com
或nslookup www.baidu.com 127.0.0.1
都报告查询超时出错，这个应该是正常的
然后再打入ping www.baidu.com ，就非常顺利地解析出地址并且ping通了（不能理解）

然后打开IE，firefox，chrome等3种浏览器，访问nstool.netease.com，都一致报告DNS服务器地址使用的是本身运营商的DNS地址，好像就跟网卡DNS地址没有被设置为127.0.0.1而采用自动获取DNS地址一样

为免ping的影响，退出所有程序及浏览器，清除DNS缓存，重启程序，重复上面的步骤直到打完两种nslookup命令，都报告超时出错，然后直接打开3个浏览器访问nstool.netease.com并刷新浏览器页面，然后3个浏览器还是一致报告DNS服务器地址使用的是本身运营商的DNS地址

这里的问题是既然网卡DNS都被设置为主，备地址都是127.0.0.1了，而且nslookup都查询出错了，为什么还能使用原来运营商的DNS去解析域名导致能够ping及浏览呢？

另外主，备DOH服务器都选程序内置列表的https://1.1.1.1/dns-query可以直接IP地址运作的项了，理论上和网卡设置什么DNS没有任何关系了，除非选的是程序内置列表那些域名URL的DOH服务器才需要网卡的DNS服务器解析这个DOH域名（这个更不理解）

**Comment by mili-tan** [comment]
你好 请提供你的配置文件config.json的内容和nslookup的截图 以便我了解更多以判断问题 谢谢
 
---原始邮件---
发件人: "quaggalinux"<notifications@github.com&gt;
发送时间: 2020年11月2日 02:46:28
收件人: "mili-tan/AuroraDNS.GUI"<AuroraDNS.GUI@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [mili-tan/AuroraDNS.GUI] 奇怪的问题（201031 - Release） (#53)




 
使用201031 - Release版本
 
设置备用dns为127.0.0.1
 
主DOH服务器选程序内置列表的第一项https://1.1.1.1/dns-query
 备DOH服务器选程序内置列表的第二项https://1.0.0.1/dns-query
 
点选设置菜单顶上的清除DNS缓存，然后点确定，保存配置，退出程序，再重启程序，然后在CMD命令行打命令ipconfig /all确认网卡的主，备DNS地址均为127.0.0.1
 
按照我理解的逻辑理论上在这个设置下可能出现两种情况
 第一，由于网卡的主，备DNS服务器地址均被设置为127.0.0.1，程序不能通过备用DNS地址查找DOH服务器，所以导致系统不能解析任何域名
 第二，由于网卡的主，备DNS服务器地址均被设置为127.0.0.1，而由于在程序中选择了https://1.1.1.1/dns-query方式的直接IP访问DOH服务器方式，所以系统可以通过DOH查询到域名
 
但是实际情况非常奇怪，当按照前面的设置重启程序，然后在CMD命令行打命令ipconfig /all确认网卡的主，备DNS地址均为127.0.0.1
 然后在CMD命令行打入nslookup www.baidu.com
 或nslookup www.baidu.com 127.0.0.1
 都报告查询超时出错，这个应该是正常的
 然后再打入ping www.baidu.com ，就非常顺利地解析出地址并且ping通了（不能理解）
 
然后打开IE，firefox，chrome等3种浏览器，访问nstool.netease.com，都一致报告DNS服务器地址使用的是本身运营商的DNS地址，好像就跟网卡DNS地址没有被设置为127.0.0.1而采用自动获取DNS地址一样
 
为免ping的影响，退出所有程序及浏览器，清除DNS缓存，重启程序，重复上面的步骤直到打完两种nslookup命令，都报告超时出错，然后直接打开3个浏览器访问nstool.netease.com并刷新浏览器页面，然后3个浏览器还是一致报告DNS服务器地址使用的是本身运营商的DNS地址
 
这里的问题是既然网卡DNS都被设置为主，备地址都是127.0.0.1了，而且nslookup都查询出错了，为什么还能使用原来运营商的DNS去解析域名导致能够ping及浏览呢？
 
另外主，备DOH服务器都选程序内置列表的https://1.1.1.1/dns-query可以直接IP地址运作的项了，理论上和网卡设置什么DNS没有任何关系了，除非选的是程序内置列表那些域名URL的DOH服务器才需要网卡的DNS服务器解析这个DOH域名（这个更不理解）

**Comment by mili-tan** [comment]
另外，当客户端启用时nslookup 127.0.0.1应当能够正确响应，请检查您的配置。
此外，请勿将程序内部备用DNS地址设为127.0.0.1以免造成回环。
 
---原始邮件---
发件人: "quaggalinux"<notifications@github.com&gt;
发送时间: 2020年11月2日 02:46:28
收件人: "mili-tan/AuroraDNS.GUI"<AuroraDNS.GUI@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [mili-tan/AuroraDNS.GUI] 奇怪的问题（201031 - Release） (#53)




 
使用201031 - Release版本
 
设置备用dns为127.0.0.1
 
主DOH服务器选程序内置列表的第一项https://1.1.1.1/dns-query
 备DOH服务器选程序内置列表的第二项https://1.0.0.1/dns-query
 
点选设置菜单顶上的清除DNS缓存，然后点确定，保存配置，退出程序，再重启程序，然后在CMD命令行打命令ipconfig /all确认网卡的主，备DNS地址均为127.0.0.1
 
按照我理解的逻辑理论上在这个设置下可能出现两种情况
 第一，由于网卡的主，备DNS服务器地址均被设置为127.0.0.1，程序不能通过备用DNS地址查找DOH服务器，所以导致系统不能解析任何域名
 第二，由于网卡的主，备DNS服务器地址均被设置为127.0.0.1，而由于在程序中选择了https://1.1.1.1/dns-query方式的直接IP访问DOH服务器方式，所以系统可以通过DOH查询到域名
 
但是实际情况非常奇怪，当按照前面的设置重启程序，然后在CMD命令行打命令ipconfig /all确认网卡的主，备DNS地址均为127.0.0.1
 然后在CMD命令行打入nslookup www.baidu.com
 或nslookup www.baidu.com 127.0.0.1
 都报告查询超时出错，这个应该是正常的
 然后再打入ping www.baidu.com ，就非常顺利地解析出地址并且ping通了（不能理解）
 
然后打开IE，firefox，chrome等3种浏览器，访问nstool.netease.com，都一致报告DNS服务器地址使用的是本身运营商的DNS地址，好像就跟网卡DNS地址没有被设置为127.0.0.1而采用自动获取DNS地址一样
 
为免ping的影响，退出所有程序及浏览器，清除DNS缓存，重启程序，重复上面的步骤直到打完两种nslookup命令，都报告超时出错，然后直接打开3个浏览器访问nstool.netease.com并刷新浏览器页面，然后3个浏览器还是一致报告DNS服务器地址使用的是本身运营商的DNS地址
 
这里的问题是既然网卡DNS都被设置为主，备地址都是127.0.0.1了，而且nslookup都查询出错了，为什么还能使用原来运营商的DNS去解析域名导致能够ping及浏览呢？
 
另外主，备DOH服务器都选程序内置列表的https://1.1.1.1/dns-query可以直接IP地址运作的项了，理论上和网卡设置什么DNS没有任何关系了，除非选的是程序内置列表那些域名URL的DOH服务器才需要网卡的DNS服务器解析这个DOH域名（这个更不理解）

**Comment by quaggalinux** [comment]
经过反复试验。可能找出原因，正常来说如果手动把网卡的DNS地址全部设置为127.0.0.1，并确定后，系统托盘的网卡图标都会马上会显示感叹号，报告没有互联网连接
而按照前面的配置步骤，即使反复清除DNS缓存，反复确认网卡的主，备DNS被AuroraDNS设置为127.0.0.1，都要经过至少3分钟以上，ping命令及浏览器访问网站才会出现网站域名解析出错的报告，而在这段时间之前，ping命令及浏览器都会使用原运营商DNS地址进行解析，但nslookup就比较奇怪了，只要确认网卡的主，备DNS被AuroraDNS设置为127.0.0.1，nslookup马上查询超时出错，所以才会导致前面试验的奇怪现象

**Comment by quaggalinux** [comment]
经过反复试验。可能找出原因，正常来说如果手动把网卡的DNS地址全部设置为127.0.0.1，并确定后，系统托盘的网卡图标都会马上会显示感叹号，报告没有互联网连接
而按照前面的配置步骤，即使反复清除DNS缓存，反复确认网卡的主，备DNS被AuroraDNS设置为127.0.0.1，都要经过至少3分钟以上，ping命令及浏览器访问网站才会出现网站域名解析出错的报告，而在这段时间之前，ping命令及浏览器都会使用原运营商DNS地址进行解析，但nslookup就比较奇怪了，只要确认网卡的主，备DNS被AuroraDNS设置为127.0.0.1，nslookup马上查询超时出错，所以才会导致前面试验的奇怪现象
