### ISSUE TITLE
可以设置本地缓存时间么，想通过这个也加速dns查询速度

### ISSUE THREAD

**Issue by zhezhe168** [mili-tan/AuroraDNS.GUI#54]

**Comment by mili-tan** [comment]
本地缓存时间目前是跟随DNS记录的TTL时间。

**Comment by zhezhe168** [comment]
可以手动指定时间么，不遵循ttl

**Comment by mili-tan** [comment]
你好 感谢你的建议
我已经添加了TTL重写功能 作为实验性的功能
你可以在[这里](https://ci.appveyor.com/project/mili-tan/auroradns-gui/builds/36984612/artifacts)下载自动化编译使用，并手动编辑 `config.json` 中 `TTLRewrite` 和 `TTLMinTime` 来启用它
当TTL小于设定值时 它将被重写为设定值

**Comment by zhezhe168** [comment]
config.json貌似没看到，这个文件是在哪里的

**Comment by zhezhe168** [comment]
哦我看到了，启动后自动生成的
