### ISSUE TITLE
请问能不能加个功能测试dns解析响应速度呢？不是ping那种，要dns成功响应的ms延迟

### ISSUE THREAD

**Issue by 1265578519** [mili-tan/AuroraDNS.GUI#55]
请问能不能加个功能测试dns解析响应速度呢？不是ping那种，要dns成功响应的ms延迟

**Comment by mili-tan** [comment]
它[现在](https://ci.appveyor.com/project/mili-tan/auroradns-gui/builds/37002056/artifacts)已经和你所想的一样了 :-D

**Comment by 1265578519** [comment]
> 它[现在](https://ci.appveyor.com/project/mili-tan/auroradns-gui/builds/37002056/artifacts)已经和你所想的一样了 :-D

！刚下载后发现没找到入口在哪，能方便截个图位置在哪吗
![image](https://user-images.githubusercontent.com/6442439/103149901-1efeeb00-47a9-11eb-828a-fdb764d1c92b.png)
![image](https://user-images.githubusercontent.com/6442439/103149905-2d4d0700-47a9-11eb-8a73-2fff5371aab6.png)

**Comment by mili-tan** [comment]
点击选择服务器旁边的小旗子标志就是测速了。

**Comment by 1265578519** [comment]
> 点击选择服务器旁边的小旗子标志就是测速了。

嗯嗯，那个列表存储在哪个文件，可以修改设置我自己需要的dns服务器测速

**Comment by mili-tan** [comment]
![图片](https://user-images.githubusercontent.com/24996957/103150192-a9951980-47ac-11eb-9e4c-a023f196e4f6.png)
右键标题导入

**Comment by 1265578519** [comment]
> ![图片](https://user-images.githubusercontent.com/24996957/103150198-c3366100-47ac-11eb-839d-440be5b646d7.png)
> 右键标题导入

感谢！不说的话真还找不到这个入口位置
