### ISSUE TITLE
Error: 尝试读取配置文件失败

### ISSUE THREAD

**Issue by NyaaGitty** [mili-tan/AuroraDNS.GUI#56]
Original error: System.MissingMethodException: Method not found: '!!0[]
System.Array.Empty()'.
    at MojoUnity.JsonValue.AsObjectGet(String Key)
    at AuroraGUI.DnsSvr.DnsSetting.Redconfig(String path)
    at AuroraGUI.MainWindows..ctor()
每次打开应用都会弹出错误如上弹窗，并自动使用初始设置。
在应用内修改设置后，在应用文件夹内的config.json内可以看到用户设置的内容。
但重启应用还会如上报错。
config.json内依然可以看到之前用户设置的内容。
文件夹路径：E:\software\AuroraDNS

感谢大大的作品，一直以来极大帮助普通人使用DoH。感谢~~~

**Comment by mili-tan** [comment]
你好&nbsp;
请检查一下配置文件是否有误 很有可能是配置文件内格式存在错误&nbsp;
你也可以尝试删除配置文件恢复默认配置后重新生成
以及目录读写权限是否正常


 
---原始邮件---
发件人: "NyaaGitty"<notifications@github.com&gt;
发送时间: 2021年2月26日 22:22:25
收件人: "mili-tan/AuroraDNS.GUI"<AuroraDNS.GUI@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [mili-tan/AuroraDNS.GUI] Error: 尝试读取配置文件失败 (#56)




 
Original error: System.MissingMethodException: Method not found: '!!0[]
 System.Array.Empty()'.
 at MojoUnity.JsonValue.AsObjectGet(String Key)
 at AuroraGUI.DnsSvr.DnsSetting.Redconfig(String path)
 at AuroraGUI.MainWindows..ctor()
 每次打开应用都会弹出错误如上弹窗，并自动使用初始设置。
 在应用内修改设置后，在应用文件夹内的config.json内可以看到用户设置的内容。
 但重启应用还会如上报错。
 config.json内依然可以看到之前用户设置的内容。
 文件夹路径：E:\software\AuroraDNS
 
感谢大大的作品，一直以来极大帮助普通人使用DoH。感谢~~~

**Comment by NyaaGitty** [comment]
感谢快速解答
（windows7 sp1系统，目录具有“修改、读取、执行、写入”四个权限，用户账户为管理员账户。）
删除配置文件后重新生成，依然是这个问题，配置复制如下：
{
"Listen" : "127.0.0.1",
"SecondDns" : "1.1.1.1",
"BlackList" : false,
"ChinaList" : false,
"RewriteList" : true,
"DebugLog" : false,
"EDnsCustomize" : false,
"EDnsClientIp" : "0.0.0.0",
"ProxyEnable" : false,
"HttpsDns" : "https://dns-family.adguard.com/dns-query",
"SecondHttpsDns" : "https://1.1.1.1/dns-query",
"Proxy" : "127.0.0.1:1080",
"EnableDnsCache" : true,
"EnableDnsMessage" : false,
"EnableAutoCleanLog" : false,
"Ipv6Disable" : false,
"Ipv4Disable" : false,
"StartupOverDoH" : false,
"AllowSelfSignedCert" : false,
"AllowAutoRedirect" : true,
"HTTPStatusNotify" : false,
"TTLRewrite" : false,
"TTLMinTime" : 300,
"EnableHttp2" : false 
}

**Comment by mili-tan** [comment]
你好，
我尝试了一下，你的配置文件在我的设备上工作正常，应该不是配置文件格式问题（我也无法复现这个问题）。
请再次检查一下配置及目录权限，以及路径中是否存在特殊字符，必要的情况下请尝试给予Everyone相关读写权限（虽然这也许不是一个好主意），还有杀毒软件等相关可能影响到读写文件的因素。
如果这都不行，我也是实在不知道应该怎么办了

**Comment by mili-tan** [comment]
还有，更新 [ .NET Framework 4.6.2](https://dotnet.microsoft.com/download/dotnet-framework/net462)
