### ISSUE TITLE
53 端口被占用

### ISSUE THREAD

**Issue by litcc** [mili-tan/AuroraDNS.GUI#57]
看过之前别人提的 issues #2 
但是因为hyper-v要用到，而且在53端口被hyper-v占用的情况下我依旧可以正常使用SimpleDNSCrypt，不清楚他是怎么在53端口被占用的情况下还可以使用，但是现在不想再使用SimpleDNSCrypt了，因为用那个访问国内网页卡出翔  :(  

作者大大有空的话可以看看这个问题。

**Comment by mili-tan** [comment]
我没有任何思路
：-（


 
---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年3月20日 14:24:21
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [mili-tan/AuroraDNS.GUI] 53 端口被占用 (#57)




 
看过之前别人提的 issues #2
 但是因为hyper-v要用到，而且在53端口被hyper-v占用的情况下我依旧可以正常使用SimpleDNSCrypt，不清楚他是怎么在53端口被占用的情况下还可以使用，但是现在不想再使用SimpleDNSCrypt了，因为用那个访问国内网页卡出翔  :(
 
作者大大有空的话可以看看这个问题。

**Comment by litcc** [comment]
没事大佬

上面说的那个 SimpleDnsCrypt ，我看他也是c#写的，大佬可以参考一下，我不是写c#的，看不懂，帮不了您
https://github.com/bitbeans/SimpleDnsCrypt


实在不行就忽略他，close，哈哈

**Comment by mili-tan** [comment]
实在抱歉，让你失望了
但是确实目前，我还没有找到正确实现该功能的合适方式。
