### ISSUE TITLE
能添加ipv6 dns吗？

### ISSUE THREAD

**Issue by toolor** [mili-tan/AuroraDNS.GUI#58]

**Comment by mili-tan** [comment]
当本地监听地址为IPv6地址时 包含对IPv6 DNS的设置


 
---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年3月25日 15:31:29
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [mili-tan/AuroraDNS.GUI] 能添加ipv6 dns吗？ (#58)
