### ISSUE TITLE
自定义IP监听地址未在即时生效

### ISSUE THREAD

**Issue by Gaukas** [mili-tan/AuroraDNS.GUI#59]
失礼了，项目真的很好。
在 设置 - IP 设置 - 自定义IP监听地址 的改变不能及时生效，必须在之后重设该程式以生效。

**Comment by mili-tan** [comment]
您好，感谢您的反馈，不出意外这将在下一个版本得到修复。

**Comment by mili-tan** [comment]
你好，该问题已被修复。
您可以在 [这里](https://ci.appveyor.com/project/mili-tan/AuroraDNS-GUI/build/artifacts) 下载自动化编译试用。
