### ISSUE TITLE
关于软件的BUG和一个建议

### ISSUE THREAD

**Issue by FanhuaCloud** [mili-tan/AuroraDNS.GUI#6]
![avatar](https://s2.ax1x.com/2019/01/17/kps7Ie.jpg)
另外建议就是 能把这个软件做成一个服务，直接运行在后台，界面只用来修改配置

**Comment by mili-tan** [comment]
额…我的环境暂时无法复现问题，您是否是在尝试打开设置窗口的时候发生错误？以及您是否设置了代理服务器？

**Comment by FanhuaCloud** [comment]
设置了，发生错误的时候设置窗口并没有被打开，也不是在打开设置窗口的时候发生的错误

**Comment by mili-tan** [comment]
您确认代理服务器设置无误吗？另外您设置的是HTTP还是HTTPS代理呢？

**Comment by FanhuaCloud** [comment]
代理服务器是没有问题的，使用的是HTTP代理

**Comment by mili-tan** [comment]
有可能是因为代理服务器兼容的问题，但是我的环境暂时始终无法复现问题。
下个 Releases 版本我会尝试把默认 TLS 版本协议枚举用或形式全都写出来，来尝试看看能否解决。
那么您在不使用代理服务器的时候能够正常使用吗？（您可以手动编辑 config.json 来修改配置文件，或者直接删除 config.json 以恢复默认配置）

**Comment by FanhuaCloud** [comment]
应该是能正常使用的，这问题我现在也很难复现
