### ISSUE TITLE
开机启动，每次都要弹出错误。

### ISSUE THREAD

**Issue by lukemin** [mili-tan/AuroraDNS.GUI#60]
![8318bc200c21ed89a4ac2b723b73979](https://user-images.githubusercontent.com/12003375/117424473-65810500-af54-11eb-9770-b00dc87bd7f2.png)

**Comment by mili-tan** [comment]
你好
你可以在设置界面左下方的“自订列表/区域化”界面中更换WhatIsMyIp API来尝试能否解决问题。
以及请在开机启动时保证可用的互联网连接。
 
---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年5月7日 16:51:34
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [mili-tan/AuroraDNS.GUI] 开机启动，每次都要弹出错误。 (#60)

**Comment by lukemin** [comment]
全都试过了，不行。开机后能够联网，并且单独访问网址都能打开。

**Comment by lukemin** [comment]
`Try Connect:System.Net.WebException: 无法连接到远程服务器 ---> System.Net.Sockets.SocketException: 由于目标计算机积极拒绝，无法连接。 127.0.0.1:1080
   在 System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   在 System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   在 System.Net.WebClient.DownloadString(Uri address)
   在 System.Net.WebClient.DownloadString(String address)
   在 AuroraGUI.Tools.IpTools.GetIntIp()
| - Catch WebException : 未将对象引用设置到对象的实例。 | Timeout | ip.rootnet.in | https://1.0.0.1/dns-query?ct=application/dns-json&name=ip.rootnet.in&type=A&edns_client_subnet=0.0.0.0
System.ArgumentOutOfRangeException: 索引超出范围。必须为非负值并小于集合大小。
参数名: index
   在 System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   在 AuroraGUI.Tools.IpTools.ResolveNameIpAddress(String name)
Try Connect:System.Net.WebException: 基础连接已经关闭: 发送时发生错误。 ---> System.IO.IOException: 由于远程方已关闭传输流，身份验证失败。
   在 System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   在 System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   在 System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   在 System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   在 System.Net.Security.SslState.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest)
   在 System.Net.Security.SslState.ProcessAuthentication(LazyAsyncResult lazyResult)
   在 System.Net.TlsStream.CallProcessAuthentication(Object state)
   在 System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   在 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   在 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   在 System.Net.TlsStream.ProcessAuthentication(LazyAsyncResult result)
   在 System.Net.TlsStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   在 System.Net.PooledStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   在 System.Net.ConnectStream.WriteHeaders(Boolean async)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   在 System.Net.WebClient.DownloadString(Uri address)
   在 System.Net.WebClient.DownloadString(String address)
   在 AuroraGUI.Tools.IpTools.GetIntIp()`

**Comment by mili-tan** [comment]
您可能无法正常访问1.0.0.1，请尝试更换DoH服务器

**Comment by lukemin** [comment]
![微信截图_20210510083037](https://user-images.githubusercontent.com/12003375/117592130-08f73300-b16a-11eb-80f4-99bc6ebcabe8.png)

**Comment by mili-tan** [comment]
请检查配置文件中的StartupOverDoH是否为true 若为true请尝试更改为false
以及请尝试提供您的网络下对1.0.0.1的ping结果

**Comment by mili-tan** [comment]
您好我将在下一个版本添加可以更换的StartupDoH IP，
以及请您检查127.0.0.1:1080是否为您的系统代理服务器，和您的系统代理服务器设置。

**Comment by lukemin** [comment]
127.0.0.1:1080是代理服务器，但是只用被gfw的网址才走。

**Comment by mili-tan** [comment]
请检查您是否使用了错误类型的代理服务器或禁用代理服务器后能否正常使用。

**Comment by lukemin** [comment]
代理服务器没有问题，就是1.0.0.1不能访问造成的。

**Comment by mili-tan** [comment]
您可以在 [这里](https://ci.appveyor.com/project/mili-tan/AuroraDNS-GUI/build/artifacts) 下载自动化编译试用，
并将StartupOverDoH启用，及将StartupDoHIp更换为Cloudflare DNS的其他地址如1.1.1.1 1.1.1.2 1.1.1.3 1.0.0.2 1.0.0.3
来尝试能否解决问题。

**Comment by lukemin** [comment]
![微信截图_20210517162054](https://user-images.githubusercontent.com/12003375/118456814-f8c3f280-b72b-11eb-9894-decf61e41589.png)
自动编译的没有问题，但是.net5.0版本的，点击按钮只能是重置为自动获取，而设为系统dns，必须关掉app，再打开才可以。

**Comment by mili-tan** [comment]
请不要使用.net5.0版本 还在测试中可能存在各种问题


 
---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年5月17日 16:24:17
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"Milkey ***@***.***&gt;;
主题: Re: [mili-tan/AuroraDNS.GUI] 开机启动，每次都要弹出错误。 (#60)




 

 自动编译的没有问题，但是.net5.0版本的，点击按钮只能是重置为自动获取，而设为系统dns，必须关掉app，再打开才可以。

**Comment by lukemin** [comment]
> 请不要使用.net5.0版本 还在测试中可能存在各种问题
使用旧版，完美解决。谢谢。
