### ISSUE TITLE
ipv6无法正常监听

### ISSUE THREAD

**Issue by dev-techmoe** [mili-tan/AuroraDNS.GUI#61]
使用版本：[210301](https://github.com/mili-tan/AuroraDNS.GUI/releases/tag/)  
尝试手动配置自定义监听地址为`::`检查后发现并无实际监听，`netstat -ano | findstr 53` 并无对应监听出现，希望关注一下这个问题  

  
另外[这个issue](https://github.com/mili-tan/AuroraDNS.GUI/issues/22#issuecomment-526916817)中提到的TCP转发目前有在程序中实现吗，似乎我没有找到对应设置项。

**Comment by mili-tan** [comment]
你好，
210301存在修改监听后可能未能即时生效的问题，请尝试重启程序后能否生效。
您也可以在 https://ci.appveyor.com/project/mili-tan/AuroraDNS-GUI/build/artifacts 下载之后版本的自动编译(请不要使用其中的net5.0对应版本)


 
---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年6月12日 12:13:08
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [mili-tan/AuroraDNS.GUI] ipv6无法正常监听 (#61)




 
使用版本：210301
 尝试手动配置自定义监听地址为::检查后发现并无实际监听，netstat -ano | findstr 53 并无对应监听出现，希望关注一下这个问题
 
另外这个issue中提到的TCP转发目前有在程序中实现吗，似乎我没有找到对应设置项。

**Comment by dev-techmoe** [comment]
> 你好， 210301存在修改监听后可能未能即时生效的问题，请尝试重启程序后能否生效。 您也可以在 https://ci.appveyor.com/project/mili-tan/AuroraDNS-GUI/build/artifacts 下载之后版本的自动编译(请不要使用其中的net5.0对应版本)
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2021年6月12日 12:13:08 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: [mili-tan/AuroraDNS.GUI] ipv6无法正常监听 (#61) 使用版本：210301 尝试手动配置自定义监听地址为::检查后发现并无实际监听，netstat -ano | findstr 53 并无对应监听出现，希望关注一下这个问题 另外这个issue中提到的TCP转发目前有在程序中实现吗，似乎我没有找到对应设置项。 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

感谢回复。使用这个地址下载的版本的修改监听地址功能正常了  
另外请问关于ipv4/ipv6同时侦听的需求，目前有实现吗？

**Comment by mili-tan** [comment]
当前版本在监听IPv6 Localback/Any地址后应该会默认同时启动对IPv4对应地址的监听

**Comment by dev-techmoe** [comment]
> 当前版本在监听IPv6 Localback/Any地址后应该会默认同时启动对IPv4对应地址的监听

经过测试发现，当手动修改监听地址为`::1`并点击保存之后，这个功能并没有马上生效，在程序中手动重新启动服务器也无法正常工作，只有在重新启动整个AuroraDNSGUI之后才有正常的`127.0.0.1:53`的侦听。测试版本：`1.0.0.0(210519.Nightly)`稳定复现。  
重启GUI之后的所有功能工作正常。

**Comment by mili-tan** [comment]
最新测试版已修复，您可以重新下载使用 




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mili-tan/AuroraDNS.GUI"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月13日(星期天) 晚上9:51
***@***.***&gt;;
抄送:&nbsp;"Milkey Tan ***@***.******@***.***&gt;;
主题:&nbsp;Re: [mili-tan/AuroraDNS.GUI] ipv6无法正常监听 (#61)





  
当前版本在监听IPv6 Localback/Any地址后应该会默认同时启动对IPv4对应地址的监听
  
经过测试发现，当手动修改监听地址为::1并点击保存之后，这个功能并没有马上生效，在程序中手动重新启动服务器也无法正常工作，只有在重新启动整个AuroraDNSGUI之后才有正常的127.0.0.1:53的侦听。测试版本：1.0.0.0(210519.Nightly)稳定复现。
 重启GUI之后的所有功能工作正常。

**Comment by dev-techmoe** [comment]
`210613.Nightly` 似乎并没有解决这个问题

**Comment by mili-tan** [comment]
请您重新测试，新的监听和配置更改都将在关闭设置窗口被应用。
