### ISSUE TITLE
电脑好像DNS中毒了，只能上QQ打不开网页用这个软件没办法突破嘛

### ISSUE THREAD

**Issue by 1265578519** [mili-tan/AuroraDNS.GUI#62]
电脑好像DNS中毒了，只能上QQ打不开网页用这个软件没办法突破嘛

已经做的事情如下，版本为AuroraDNS.GUI.210201
nslookup www.baidu.com 127.0.0.1 响应正常
但是ping就提示找不到主机，网卡已确保ipv4的dns为127.0.0.1
测试浏览器等任何其它应用均无法使用，只有QQ可以正常

已经尝试使用lsp修复命令并且重启系统
netsh winsock reset

通过开始菜单系统设置，网络重启，并且重启系统

但是在chrome中单独进行安全设置doh加密，就可以正常浏览网页了。

同时，通过手机开放USB热点给电脑连接，网络可以一切正常解析和访问。基本上可以定位到是学校网络出现了异常

并且在QQ群 群友中经过测试，在系统Windows防火墙中封堵UDP53出向端口的情况下，可以正常使用AuroraDNS该软件来解析，就是启动设置DNS的时候会很卡，要等待5秒才能提示成功，并且DOH服务器一定要为IP
![image](https://user-images.githubusercontent.com/6442439/123460046-a2df4600-d619-11eb-993e-bbaf398ac828.png)

这种情况有什么解决办法嘛，有其他人遇到没？如果没有办法的话只能重装系统试试了

话说能不能整合成一个选项？直接点击退出，会导致网卡还保留127.0.0.1
![image](https://user-images.githubusercontent.com/6442439/123460352-14b78f80-d61a-11eb-889a-4d6b33fc2a7c.png)

**Comment by mili-tan** [comment]
您好 请直接将备用DNS服务器置为空值 以及确保配置文件中的StartupOverDoH为true
这将会使启动时的初始查询使用基于IP地址的DoH服务器进行查询
以及退出选项不合并 是为了防止意外退出和每次关机/开机自启动时等情况下无法提升管理员权限对DNS进行修改。

**Comment by 1265578519** [comment]
感谢分析，确认了下StartupOverDoH默认值已为true，刚重装完系统后就好了，估计是中毒了
