### ISSUE TITLE
开机报错

### ISSUE THREAD

**Issue by leafsnow** [mili-tan/AuroraDNS.GUI#63]
![QQ截图20210702215327](https://user-images.githubusercontent.com/6291246/124284952-0a4c4700-db80-11eb-91df-56efc4e52ae6.png)
![image](https://user-images.githubusercontent.com/6291246/124285056-28b24280-db80-11eb-9d98-6facfa2c0ae9.png)

请教大佬，本来可以用的，然后按照了GotoX尝试一下，又把GotoX卸载，然后就一直报错这个了。

**Comment by leafsnow** [comment]
![image](https://user-images.githubusercontent.com/6291246/124285820-e50c0880-db80-11eb-84d2-34107a60132c.png)

明明可以联网的，搜索到类似的贴子，大佬提到的几步，除了自己编译一个，都尝试了。

**Comment by leafsnow** [comment]
![QQ截图20210702220124](https://user-images.githubusercontent.com/6291246/124285995-108ef300-db81-11eb-8507-12f0fad5af3c.png)

**Comment by mili-tan** [comment]
请检查代理服务器是否正常
无法访问到代理服务器
请尝试关闭使用代理服务器选项或更换代理服务器
 
---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年7月2日 22:01:50
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: Re: [mili-tan/AuroraDNS.GUI] 开机报错 (#63)

**Comment by leafsnow** [comment]
我是本地代理，关闭了 设置中的 使用代理 还是报了一样的问题

**Comment by leafsnow** [comment]
谢谢大佬，关闭代理，打开自定义监听IP就好了。

**Comment by mili-tan** [comment]
请点击确认以保存 或直接删除程序目录下config.json配置文件以恢复默认配置


 
---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年7月2日 22:11:51
收件人: ***@***.***&gt;;
抄送: "Milkey ***@***.******@***.***&gt;;
主题: Re: [mili-tan/AuroraDNS.GUI] 开机报错 (#63)




 
我是本地代理，关闭了 设置中的 使用代理 还是报了一样的问题
