### ISSUE TITLE
有计划发新版本吗

### ISSUE THREAD

**Issue by qingchuwudi** [mili-tan/AuroraDNS.GUI#67]
如题，请问近期有计划发布一个新的版本吗

**Comment by mili-tan** [comment]
您好，目前您可以在[https://ci.appveyor.com/project/mili-tan/AuroraDNS-GUI/build/artifacts](https://ci.appveyor.com/project/mili-tan/AuroraDNS-GUI/build/artifacts) 下载最新的自动化编译版本。

**Comment by qingchuwudi** [comment]
> 您好，目前您可以在https://ci.appveyor.com/project/mili-tan/AuroraDNS-GUI/build/artifacts 下载最新的自动化编译版本。

非常感谢！
