### ISSUE TITLE
错误错误错误

### ISSUE THREAD

**Issue by sonic732** [mili-tan/AuroraDNS.GUI#68]
新版本错误错误错误
![捕1获](https://user-images.githubusercontent.com/70852930/150307472-f18ec3c0-2a81-4ac8-b982-9de0f196fe4e.PNG)
![捕获](https://user-images.githubusercontent.com/70852930/150307480-67ef943f-9793-42fb-9811-57b200cdd3e7.PNG)

**Comment by mili-tan** [comment]
您好，目前您可以在 https://ci.appveyor.com/project/mili-tan/AuroraDNS-GUI/build/artifacts 下载最新的自动化编译版本，此版本可能解决了您的问题。

**Comment by sonic732** [comment]
您好大佬！已经改回原来版本使用了！大佬加油，用你的软件好几年了！好评如潮！

**Comment by mili-tan** [comment]
> 您好大佬！已经改回原来版本使用了！大佬加油，用你的软件好几年了！好评如潮！

谢谢您的支持，提前祝您农历新年快乐！
