### ISSUE TITLE
最新版的报错，win7环境，已安装framework 4.7.2

### ISSUE THREAD

**Issue by zhezhe168** [mili-tan/AuroraDNS.GUI#69]

**Comment by mili-tan** [comment]
请提供截图或者错误信息


 
---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年2月15日 10:50:18
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [mili-tan/AuroraDNS.GUI] 最新版的报错，win7环境，已安装framework 4.7.2 (Issue #69)
