### ISSUE TITLE
老版本也报错

### ISSUE THREAD

**Issue by zhezhe168** [mili-tan/AuroraDNS.GUI#70]
Object reference not set to an instance of an object. | TrustFailure

win7

![image](https://user-images.githubusercontent.com/10943213/154205538-d7110d3b-1bda-4515-8cd8-9867a74dbf62.png)

**Comment by mili-tan** [comment]
您好，这可能是您的网络问题。
您可能无法正常连接到 1.0.0.1，请尝试更换备用 DoH 服务器。
请使用新版本 AuroraDNS，
手动编辑config.json来将StartupOverDoH启用或停用，
及将StartupDoHIp更换为Cloudflare DNS的其他地址如1.1.1.1 1.1.1.2 1.1.1.3 1.0.0.2 1.0.0.3
来尝试能否解决问题。

**Comment by 1265578519** [comment]
你这个问题和我以前的差不多吧，，https://github.com/mili-tan/AuroraDNS.GUI/issues/66
实测可以改为
```
"StartupDoHIp" : "1.12.12.12",
```

**Comment by zhezhe168** [comment]
我试了下，1.0.0.1可以正常打开，不知道为什么还报错。。。

**Comment by 1265578519** [comment]
> 我试了下，1.0.0.1可以正常打开，不知道为什么还报错。。。

最简单的测试命令，你试一下，浏览器能打开，不代表流量没被阻断能正常使用dns
```
nslookup www.baidu.com 1.0.0.1
```
![image](https://user-images.githubusercontent.com/6442439/155704030-7dac5dcc-8e0e-4061-ba05-2d64415ec32f.png)

![image](https://user-images.githubusercontent.com/6442439/155703994-20d5ba93-030d-4c94-96b5-7a3fbc3c0afb.png)

**Comment by zhezhe168** [comment]
好的应该是这个问题，谢谢
