### ISSUE TITLE
txy最新的ip doh服务器

### ISSUE THREAD

**Issue by 1265578519** [mili-tan/AuroraDNS.GUI#71]
txy最新的ip doh服务器，腾讯最快最稳定的dns域名解析服务器

主：https://dns.pub/dns-query
备：https://doh.pub/dns-query

数据来自腾讯官网
https://dns.pub/

ip格式
主：https://1.12.12.12/dns-query
备：https://120.53.53.53/dns-query

bgp延迟更低访问速度更快
主：https://162.14.21.56/dns-query
备：https://162.14.21.178/dns-query

**Comment by mili-tan** [comment]
您好
感谢你的提议，但是腾讯dnspod的主地址已在列表中存在，我们不会添加子/备用服务器地址。
感谢你的理解。
