### ISSUE TITLE
53端口被占用，求方法

### ISSUE THREAD

**Issue by shipand** [mili-tan/AuroraDNS.GUI#75]
![image](https://user-images.githubusercontent.com/51933636/156916483-f2b78f79-21db-4871-8964-800ef9d42d1d.png)

**Comment by mili-tan** [comment]
请参考 https://github.com/mili-tan/AuroraDNS.GUI/issues/2


 
---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年3月6日 17:07:51
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [mili-tan/AuroraDNS.GUI] 53端口被占用，求方法 (Issue #75)
