### ISSUE TITLE
内存占用高

### ISSUE THREAD

**Issue by sixgodfan** [mili-tan/AuroraDNS.GUI#76]
一般占用170MB左右的内存，我觉得挺高的……
1.另外使用代理是什么意思？通过代理去解析么？
2.配合clash使用的话，需要怎么配置？谢谢

**Comment by mili-tan** [comment]
你好，若您使用 Clash 推荐使用使用 Clash 内置 DNS 功能。
内存在关闭窗口收起托盘一段时间后自动回收，使用代理的意思就是通过代理进行解析。
