### ISSUE TITLE
你好，希望能增加DNS优选功能

### ISSUE THREAD

**Issue by sky5454** [mili-tan/AuroraDNS.GUI#8]
RT

**Comment by mili-tan** [comment]
您指的是精准解析还是 ChinaDNS 类似功能呢？
精准解析的话已经支持 EDNS Client Subnet 理论上是能够精准解析的（虽然具体的情况还是依照 DoH 服务器策略）
类似 ChinaDNS 的话已经在 Core 中实现了，大概近期会在 GUI 上添加。

**Comment by sky5454** [comment]
指的是本机连接DNS服务器的网络状况，如延迟丢包劫持情况等等的优选

**Comment by sky5454** [comment]
指的是本机连接DNS服务器的网络状况，如延迟丢包劫持情况等等的优选

**Comment by sky5454** [comment]
指的是本机连接DNS服务器的网络状况，如延迟丢包劫持情况等等的优选

**Comment by mili-tan** [comment]
您好，你可以使用测速功能进行测试，自行选择。
因为 DNS 是一项关键的网络服务，每个提供商有不同的解析策略和隐私政策，您应该自行斟酌选择您信赖的提供商，不应该仅由延迟和丢包率来自动选定。

**Comment by sky5454** [comment]
但是优选很重要啊，或者，至少加个超时功能和状况排序吧，，其实太高延迟的直接中断显示延迟就可以了，没必要再得出多少ms。
