### ISSUE TITLE
[FEATURE REQUEST] 国内网站用国内解析

### ISSUE THREAD

**Issue by liumingedwin** [mili-tan/AuroraDNS.GUI#81]
`RT`，用海外 `DNS` 上 `GitHub` 确实快，但是国内网站变得很慢。能不能分流

**Comment by mili-tan** [comment]
请修改配置文件将ChinaList改为true，并创建ChinaList.List文件，每行一个需要分流的域名，分流域名将会使用DNSPod D+ HTTPDNS 进行解析。
