### ISSUE TITLE
取消报错弹窗

### ISSUE THREAD

**Issue by jelly0930** [mili-tan/AuroraDNS.GUI#84]
我本地防火墙关了53端口，只想使用本工具，但是会遇到如下报错

![image](https://github.com/mili-tan/AuroraDNS.GUI/assets/37065209/d465067f-1413-420e-ac31-b3f7fa7f230f)

我能想到的是修改代码取消这个报错弹窗，但是我不懂.net怎么写的，大佬能告诉我删哪的代码吗

**Comment by mili-tan** [comment]
![31d2cf217f543040a37d87d66116ba4f](https://github.com/mili-tan/AuroraDNS.GUI/assets/24996957/8334428f-adb8-4b40-bf60-5d6ed40780fe)
你好，请修改此处配置更换可用的公网IP接口
