### ISSUE TITLE
53端口占用问题，可以让软件使用其它端口吗？

### ISSUE THREAD

**Issue by jelly0930** [mili-tan/AuroraDNS.GUI#85]
总是遇到53端口被占用的情况，把ICS禁用了可以打开软件，但每次重启电脑后ICS又打开了，很麻烦，问下作者代码中哪个地方改了后可以使用其它端口呢

**Comment by mili-tan** [comment]
你好，你可以修改配置文件添加一条”Port“，即可监听其他端口。

**Comment by jelly0930** [comment]
![image](https://github.com/mili-tan/AuroraDNS.GUI/assets/37065209/5be722b1-a531-4007-b07d-4e39ddd19355)
不好意思，再问一下，我的修改好像不起作用，是哪做错了吗
