### ISSUE TITLE
运行一段时间后失效

### ISSUE THREAD

**Issue by jelly0930** [mili-tan/AuroraDNS.GUI#86]
我本地关了53端口，在windows10上运行本软件后可以正常上网，但没过一会儿就不行了，浏览器显示找不到IP，就是dns解析没走加密了。把本软件重启后又能有上一会网。这个问题有遇到过吗，会是我关了53端口的问题么

**Comment by mili-tan** [comment]
本软件依赖53端口监听的本地DNS服务器实现功能，禁用53端口会导致请求失败。
建议通过 `nslookup example.com 127.0.0.1` 来测试。

**Comment by mili-tan** [comment]
请检查本地日志，是否有错误信息

**Comment by jelly0930** [comment]
不好意思，我一直没找到日志文件在哪

**Comment by mili-tan** [comment]
请打开设置中的“记录日志”，右键托盘图标有有“查阅日志”，希望对您有所帮助。

**Comment by jelly0930** [comment]
点击查阅日志，然后弹窗一闪而过，太快了截不了图，弹窗显示找不到系统日志，未产生日志这种

**Comment by mili-tan** [comment]
建议开启“记录日志”之后重启程序，之后等待一段时间。
