### ISSUE TITLE
启动显示重复启动

### ISSUE THREAD

**Issue by Hscpro** [mili-tan/AuroraDNS.GUI#9]
![image](https://user-images.githubusercontent.com/13926044/53171790-ab28b000-361e-11e9-9cd9-98c22d6a7c86.png)

**Comment by mili-tan** [comment]
您确定没有重复运行吗？

**Comment by Hscpro** [comment]
> 您确定没有重复运行吗？（这是一个正常的在重复运行时弹出的提示）
> 此外请您更详细的描述您的问题，以便我能够解决。

我确定我没有重复运行，我尝试获取日志但是没有任何反应

**Comment by Hscpro** [comment]
还有一个问题，或许能帮助判断问题；点击右键的重新启动时候显示：
![image](https://user-images.githubusercontent.com/13926044/53245932-30c56200-36ea-11e9-9c93-b50e922e4e45.png)

**Comment by Hscpro** [comment]
有关调用实时(JIT)调试而不是此对话框的详细信息，
请参见此消息的结尾。

************** 异常文本 **************
System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 ARSoft.Tools.Net.Dns.DnsServer.Stop()
   在 AuroraGUI.MainWindow.<>c.<.ctor>b__6_1(Object sender, EventArgs args)
   在 System.ComponentModel.Component.Dispose(Boolean disposing)
   在 System.ComponentModel.Component.Dispose()
   在 AuroraGUI.MainWindow.<.ctor>b__6_2(Object sender, EventArgs args)
   在 System.Windows.Forms.MenuItem.OnClick(EventArgs e)
   在 System.Windows.Forms.MenuItem.MenuItemData.Execute()
   在 System.Windows.Forms.Command.Invoke()
   在 System.Windows.Forms.Command.DispatchID(Int32 id)
   在 System.Windows.Forms.NotifyIcon.WndProc(Message& msg)
   在 System.Windows.Forms.NotifyIcon.NotifyIconNativeWindow.WndProc(Message& m)
   在 System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** 已加载的程序集 **************
mscorlib
    程序集版本:4.0.0.0
    Win32 版本:4.7.2600.0 built by: NET471REL1LAST
    基本代码:file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
AuroraGUI
    程序集版本:1.0.0.0
    Win32 版本:1.0.0.0
    基本代码:file:///E:/System/Desktop/Release/AuroraGUI.exe
----------------------------------------
PresentationFramework
    程序集版本:4.0.0.0
    Win32 版本:4.7.2600.0
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework/v4.0_4.0.0.0__31bf3856ad364e35/PresentationFramework.dll
----------------------------------------
WindowsBase
    程序集版本:4.0.0.0
    Win32 版本:4.7.2600.0 built by: NET471REL1LAST
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/WindowsBase/v4.0_4.0.0.0__31bf3856ad364e35/WindowsBase.dll
----------------------------------------
System.Core
    程序集版本:4.0.0.0
    Win32 版本:4.7.2600.0 built by: NET471REL1LAST
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System
    程序集版本:4.0.0.0
    Win32 版本:4.7.2556.0 built by: NET471REL1
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
PresentationCore
    程序集版本:4.0.0.0
    Win32 版本:4.7.2600.0 built by: NET471REL1LAST
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_32/PresentationCore/v4.0_4.0.0.0__31bf3856ad364e35/PresentationCore.dll
----------------------------------------
System.Xaml
    程序集版本:4.0.0.0
    Win32 版本:4.7.2600.0 built by: NET471REL1LAST
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xaml/v4.0_4.0.0.0__b77a5c561934e089/System.Xaml.dll
----------------------------------------
System.Configuration
    程序集版本:4.0.0.0
    Win32 版本:4.7.2556.0 built by: NET471REL1
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    程序集版本:4.0.0.0
    Win32 版本:4.7.2556.0 built by: NET471REL1
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
MaterialDesignThemes.Wpf
    程序集版本:2.5.0.1205
    Win32 版本:2.5.0.1205
    基本代码:file:///E:/System/Desktop/Release/MaterialDesignThemes.Wpf.DLL
----------------------------------------
MaterialDesignColors
    程序集版本:1.1.3.0
    Win32 版本:1.1.3
    基本代码:file:///E:/System/Desktop/Release/MaterialDesignColors.DLL
----------------------------------------
ARSoft.Tools.Net
    程序集版本:2.2.9.0
    Win32 版本:2.2.9.0
    基本代码:file:///E:/System/Desktop/Release/ARSoft.Tools.Net.DLL
----------------------------------------
System.Windows.Forms
    程序集版本:4.0.0.0
    Win32 版本:4.7.2556.0 built by: NET471REL1
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    程序集版本:4.0.0.0
    Win32 版本:4.7.2556.0 built by: NET471REL1
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
mscorlib.resources
    程序集版本:4.0.0.0
    Win32 版本:4.7.2556.0 built by: NET471REL1
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_zh-Hans_b77a5c561934e089/mscorlib.resources.dll
----------------------------------------
PresentationFramework.Aero2
    程序集版本:4.0.0.0
    Win32 版本:4.7.2556.0 built by: NET471REL1
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework.Aero2/v4.0_4.0.0.0__31bf3856ad364e35/PresentationFramework.Aero2.dll
----------------------------------------
PresentationCore.resources
    程序集版本:4.0.0.0
    Win32 版本:4.7.2556.0 built by: NET471REL1
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/PresentationCore.resources/v4.0_4.0.0.0_zh-Hans_31bf3856ad364e35/PresentationCore.resources.dll
----------------------------------------
PresentationFramework-SystemXml
    程序集版本:4.0.0.0
    Win32 版本:4.7.2556.0
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework-SystemXml/v4.0_4.0.0.0__b77a5c561934e089/PresentationFramework-SystemXml.dll
----------------------------------------
UIAutomationTypes
    程序集版本:4.0.0.0
    Win32 版本:4.7.2600.0 built by: NET471REL1LAST
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/UIAutomationTypes/v4.0_4.0.0.0__31bf3856ad364e35/UIAutomationTypes.dll
----------------------------------------
PresentationFramework.resources
    程序集版本:4.0.0.0
    Win32 版本:4.7.2556.0
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework.resources/v4.0_4.0.0.0_zh-Hans_31bf3856ad364e35/PresentationFramework.resources.dll
----------------------------------------
System.Windows.Forms.resources
    程序集版本:4.0.0.0
    Win32 版本:4.7.2556.0 built by: NET471REL1
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_zh-Hans_b77a5c561934e089/System.Windows.Forms.resources.dll
----------------------------------------

************** JIT 调试 **************
要启用实时(JIT)调试，
该应用程序或计算机的 .config 文件(machine.config)的 system.windows.forms 节中必须设置
jitDebugging 值。
编译应用程序时还必须启用
调试。

例如:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

启用 JIT 调试后，任何未经处理的异常
都将被发送到在此计算机上注册的 JIT 调试程序，
而不是由此对话框处理。

**Comment by mili-tan** [comment]
麻烦手动检查目录下Log文件夹 如果没有文件或没有目录应是未发生错误
另外请检查 任务栏及任务管理器 是否存在多个进程。
启动多个实例时使用菜单的重新启动发生异常是逻辑问题，下个版本将会进行修复。

**Comment by Hscpro** [comment]
已确认
![image](https://user-images.githubusercontent.com/13926044/53246181-e7c1dd80-36ea-11e9-9b06-3ef2a0f872de.png)
![image](https://user-images.githubusercontent.com/13926044/53246220-0a53f680-36eb-11e9-9b97-740626727ad6.png)

**Comment by Hscpro** [comment]
> 麻烦手动检查目录下Log文件夹 如果没有文件或没有目录应是未发生错误
> 另外请检查 任务栏及任务管理器 是否存在多个进程。
> 启动多个实例时使用菜单的重新启动发生异常是逻辑问题，下个版本将会进行修复。

我尝试用一台新电脑运行还是提醒重复

**Comment by mili-tan** [comment]
啊 重复进程识别标识有误 应是53端口被占用
您可以试试看 `netstat -ano|findstr 53` 来查看53端口的占用的情况
然后可以通过对应PID `tasklist | findstr [PID]` 反查到是何程序正在占用端口

**Comment by Hscpro** [comment]
查询到是一项 SharedAccess Internet Connection Sharing (ICS) 服务占用了端口

![image](https://user-images.githubusercontent.com/13926044/53247026-412b0c00-36ed-11e9-9bc7-b7827cc5831b.png)

**Comment by mili-tan** [comment]
关于 SharedAccess 占用 53 端口的问题 也许 [Azure/service-fabric-issues#803 (comment)](https://github.com/Azure/service-fabric-issues/issues/803#issuecomment-361706326) 能够为您带来一些帮助

**Comment by Hscpro** [comment]
停用ICS 并没有问题，现在已经能正常运行。谢谢！
